import { Pieces } from "./interface";

export const pieces = [
    { piece: Pieces.pawn | Pieces.black },
    { piece: Pieces.pawn | Pieces.black },
    { piece: Pieces.pawn | Pieces.black },
    { piece: Pieces.pawn | Pieces.black },
    { piece: Pieces.pawn | Pieces.black },
    { piece: Pieces.pawn | Pieces.black },
    { piece: Pieces.pawn | Pieces.black },
    { piece: Pieces.pawn | Pieces.black },
    { piece: Pieces.pawn | Pieces.black },
    { piece: Pieces.pawn | Pieces.black },
    { piece: Pieces.knight | Pieces.black },
    { piece: Pieces.knight | Pieces.black },
    { piece: Pieces.bishop | Pieces.black },
    { piece: Pieces.bishop | Pieces.black },
	{ piece: Pieces.rook | Pieces.black },
    { piece: Pieces.queen | Pieces.black },
    { piece: Pieces.king | Pieces.black },
	{ piece: Pieces.pawn | Pieces.white },
    { piece: Pieces.pawn | Pieces.white },
    { piece: Pieces.pawn | Pieces.white },
    { piece: Pieces.pawn | Pieces.white },
    { piece: Pieces.pawn | Pieces.white },
    { piece: Pieces.pawn | Pieces.white },
    { piece: Pieces.pawn | Pieces.white },
    { piece: Pieces.pawn | Pieces.white },
    { piece: Pieces.pawn | Pieces.white },
    { piece: Pieces.pawn | Pieces.white },
    { piece: Pieces.knight | Pieces.white },
    { piece: Pieces.knight | Pieces.white },
    { piece: Pieces.bishop | Pieces.white },
    { piece: Pieces.bishop | Pieces.white },
	{ piece: Pieces.rook | Pieces.white },
    { piece: Pieces.queen | Pieces.white },
    { piece: Pieces.king | Pieces.white },
  ]